/*
 * Transactional API
 *
 * # Introduction    This API is a service provided by [E-goi](www.e-goi.com) to send transactional messages.    Transactional Messaging is a 1-to-1 communication channel, usually from an organization directed to a specific consumer.   They can be triggered by:    * __Actions__ - The consumer interacts with the organization (ie.: online shopping);  * __Time__ - The consumer's actions are time-bounded by the organization (ie.: period of inactivity).    Because of the nature of these messages,   it is expected that the consumer is interested in the content of these messages.   Therefore, they have a different treatment from marketing messages, and have a higher acceptance and opening rate.    >DISCLAIMER  >  >Please notice that this platform is more delicate in regards to the nature and processing of its messages.  >  >It should NOT be used as a mean of mass marketing, scams, phishing or overall unruly behaviour.   >  >Failure to comply may lead to limitation of use and even termination of account.    ***
 *
 * API version: V2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The message and its triggering condition
type MultiChannelMessageObject struct {
	// Available communications channels in the API. Currently there are Emails and Sms.
	Channel string `json:"channel"`
	// the interval in seconds between the message and the previous. Defaults to 3600s (1h).
	Interval int32 `json:"interval,omitempty"`
	// The condition of the previous message to trigger the next one. In list of messages in the plan the condition of the first message is discarded (doesnt have previous condition). Can be:  Name | Description | Channel --- | --- | --- none | no condition of previous message | email, sms not_open | previous message hasnt been opened | email open | previous message has been opened | email click | previous message has a link that has been clicked | email not_click | previous message has a link that has not been clicked | email
	Condition string `json:"condition,omitempty"`
	// the template id already in the system. overrides subject, textBody and htmlBody.
	TemplateId int32 `json:"templateId,omitempty"`
	// The subject of the message. Only applies to email messages.
	Subject string `json:"subject,omitempty"`
	// The text body of the message.
	TextBody string `json:"textBody,omitempty"`
	// The html body of the message. Only applies to email messages.
	HtmlBody string `json:"htmlBody,omitempty"`
}
