/*
 * Transactional API
 *
 * # Introduction    This API is a service provided by [E-goi](www.e-goi.com) to send transactional messages.    Transactional Messaging is a 1-to-1 communication channel, usually from an organization directed to a specific consumer.   They can be triggered by:    * __Actions__ - The consumer interacts with the organization (ie.: online shopping);  * __Time__ - The consumer's actions are time-bounded by the organization (ie.: period of inactivity).    Because of the nature of these messages,   it is expected that the consumer is interested in the content of these messages.   Therefore, they have a different treatment from marketing messages, and have a higher acceptance and opening rate.    >DISCLAIMER  >  >Please notice that this platform is more delicate in regards to the nature and processing of its messages.  >  >It should NOT be used as a mean of mass marketing, scams, phishing or overall unruly behaviour.   >  >Failure to comply may lead to limitation of use and even termination of account.    ***
 *
 * API version: V2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MobileAppRequest struct {
	// The name of the App
	Name string `json:"name"`
	// Option to send the notification in a Sandbox Environment in iOS devices.
	Sandbox bool `json:"sandbox"`
	// The certificate of the app
	Certificate string `json:"certificate,omitempty"`
	// The password of the certificate.
	Password string `json:"password,omitempty"`
	// The authentication key to send push messages to android.
	AuthKey string `json:"authKey,omitempty"`
}
