/*
 * Transactional API
 *
 * # Introduction    This API is a service provided by [E-goi](www.e-goi.com) to send transactional messages.    Transactional Messaging is a 1-to-1 communication channel, usually from an organization directed to a specific consumer.   They can be triggered by:    * __Actions__ - The consumer interacts with the organization (ie.: online shopping);  * __Time__ - The consumer's actions are time-bounded by the organization (ie.: period of inactivity).    Because of the nature of these messages,   it is expected that the consumer is interested in the content of these messages.   Therefore, they have a different treatment from marketing messages, and have a higher acceptance and opening rate.    >DISCLAIMER  >  >Please notice that this platform is more delicate in regards to the nature and processing of its messages.  >  >It should NOT be used as a mean of mass marketing, scams, phishing or overall unruly behaviour.   >  >Failure to comply may lead to limitation of use and even termination of account.    ***
 *
 * API version: V2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The attachment to be attached in the email.
type AttachmentRequest struct {
	// the filename of the file to go in the email.
	Filename string `json:"filename"`
	// the base64 stream of information that comprises the file.
	Data string `json:"data"`
	// the format to buuild the file for the recipient.
	MimeType string `json:"mimeType"`
	// Arrangement for the Attachment inside the email. Can be either: \"inline\" (appears inside the email message body) or \"attachment\" (appears as an enclosed file).
	Arrangement string `json:"arrangement"`
}
