/*
 * Transactional API
 *
 * # Introduction    This API is a service provided by [E-goi](www.e-goi.com) to send transactional messages.    Transactional Messaging is a 1-to-1 communication channel, usually from an organization directed to a specific consumer.   They can be triggered by:    * __Actions__ - The consumer interacts with the organization (ie.: online shopping);  * __Time__ - The consumer's actions are time-bounded by the organization (ie.: period of inactivity).    Because of the nature of these messages,   it is expected that the consumer is interested in the content of these messages.   Therefore, they have a different treatment from marketing messages, and have a higher acceptance and opening rate.    >DISCLAIMER  >  >Please notice that this platform is more delicate in regards to the nature and processing of its messages.  >  >It should NOT be used as a mean of mass marketing, scams, phishing or overall unruly behaviour.   >  >Failure to comply may lead to limitation of use and even termination of account.    ***
 *
 * API version: V2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ManualEmail struct {
	// the Domain to de used in the sender email.
	Domain string `json:"domain,omitempty"`
	// The code identification of the sender profile to be used.
	SenderId string `json:"senderId"`
	// The name to be associated with the Domain to form the email.
	SenderName string `json:"senderName,omitempty"`
	// The To field in the email.
	To []string `json:"to"`
	// The Cc field in the email.
	Cc []string `json:"cc,omitempty"`
	// The Bcc field in the email.
	Bcc []string `json:"bcc,omitempty"`
	// The email id for if/when the recipient responds to the email.
	ReplyToId string `json:"replyToId,omitempty"`
	// The subject of the message.
	Subject string `json:"subject"`
	// The html version of the body of the message.
	HtmlBody string `json:"htmlBody,omitempty"`
	// The text version of the body of the message.
	TextBody string `json:"textBody,omitempty"`
	// The option to track if the message is opened.
	OpenTracking bool `json:"openTracking,omitempty"`
	// The option to track if the message is clicked.
	ClickTracking bool `json:"clickTracking,omitempty"`
	// A list of files to be attached to the emails
	Attachment []AttachmentRequest `json:"attachment,omitempty"`
	// A list of the merge tags to replace information gaps in the email. The format of each tag should be ``tagName:tagValue``
	MergeTags []string `json:"mergeTags,omitempty"`
	// Extra Data related to the campaign to be re-sent via WebHook.
	CustomData string `json:"customData,omitempty"`
	// The priority of the message.
	Priority string `json:"priority,omitempty"`
	// option to register the message. Its an exclusive feature for senders that require it.
	Registered bool `json:"registered,omitempty"`
	Header *HeaderOptionsRequest `json:"header,omitempty"`
	// The group of the message.
	Group string `json:"group,omitempty"`
}
